app/main/__init__.py
from flask import Blueprint

# create blueprint boject
bp = Blueprint('main', __name__, template_folder='templates')

from app.main import routes

app/main/routes.py
from crypt import methods
from bs4 import Tag
from app.main import bp
from flask import jsonify, render_template, request, url_for, current_app
from app.main import util
from app import models
from app import db

@bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    questions = models.Questions.query.order_by(models.Questions.question).paginate(page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.index', page=questions.next_num) if questions.has_next else None
    prev_url = url_for('main.index', page=questions.prev_num) if questions.has_prev else None
    return render_template('main/index.html', questions = questions.items, tag="Random", next_url = next_url, prev_url = prev_url)

@bp.route('/<tag>')
def show_question(tag):
    page = request.args.get('page', 1, type=int)
    questions=models.Questions.query.filter_by(tag=tag).paginate(page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.index', page=questions.next_num) if questions.has_next else None
    prev_url = url_for('main.index', page=questions.prev_num) if questions.has_prev else None
    return render_template('main/index.html', questions = questions.items, tag = tag, next_url = next_url, prev_url = prev_url)

@bp.route('/show/questions/<id>/<question>')
@bp.route('/questions/<id>/<question>')
def show_answer(question, id):
    link = f'https://stackoverflow.com/questions/{id}/{question}'
    answer = util.answer(link)
    return render_template('main/show.html', answer=answer)

@bp.post('/questions')
def add():
    if request.is_json:
        tag = request.get_json()['tag']
        questions = util.freq_questions(tag)
        if questions:
            for question in questions:
                q1 = models.Questions(question = question['title'], link = question['link'], tag = tag)
                db.session.add(q1)
                db.session.commit()
            return jsonify({'message': 'New Question added Successfully!'}), 201
    return jsonify({'message': 'Question not added'}), 415

@bp.get('/questions')
def question():
    if request.is_json:
        tag = request.get_json()['tag']
        questions = models.Questions.query.filter_by(tag=tag).all()
        if questions:
            questions = [{'question': question.question, 'url': f"https://stackoverflow.com/questions{question.link.replace('*','/')}"} for question in questions]
            return jsonify(questions)
    return jsonify({
                        "message": "There is no question related with this tag"
                   }), 415

app/main/templates/main/base.html
{% extends "bootstrap/base.html" %}

{% block title %}
    {% if title %}
        {{title}}
    {% else %}
        Stackfaq
    {% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url_for('main.index')}}">Stackfaq</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{url_for('main.show_question', tag = 'python')}}">Python</a></li>
                    <li><a href="{{url_for('main.show_question', tag = 'php')}}">PHP</a></li>
                    <li><a href="{{url_for('main.show_question', tag = 'javascript')}}">Javascript</a></li>
                    <li><a href="{{url_for('main.show_question', tag = 'java')}}">Java</a></li>
                    <li><a href="{{url_for('main.show_question', tag = 'mysql')}}">MySQL</a></li>
                    <li><a href="{{url_for('main.show_question', tag = 'go')}}">GO</a></li>
                </ul>
            </div>
        </div>
    </nav>
{%endblock %}

{% block content %}
    <div class="container">
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block app_content %}
{% if questions %}
    {% if questions %}
        <h1>TAG: {{tag}}</h1>
    {% endif %}
        {% for question in questions %}
            <p>
                {% set link = question.link | replace('*','/') %}
                {% set link = link[1:] %}
                {% set id = link.split('/')[1] %}
                {% set ques = link.split('/')[2] %}
                 <a href="{{url_for('main.show_answer', question = ques, id = id )}}">{{ question.tag|title }}: {{question.question}}</a>
            </p>
        {% endfor %}
        <nav aria-label="...">
            <ul class="pager">
                <li class="previous{% if not prev_url %} disabled{% endif %}">
                    <a href="{{ prev_url or '#' }}">
                        <span aria-hidden="true">&larr;</span> Newer posts
                    </a>
                </li>
                <li class="next{% if not next_url %} disabled{% endif %}">
                    <a href="{{ next_url or '#' }}">
                        Older posts <span aria-hidden="true">&rarr;</span>
                    </a>
                </li>
            </ul>
        </nav>
    {% else %}
        <div>
            <h1>There is no question</h1>
        </div>
    {% endif %}
{%endblock%}

app/main/templates/main/show.html
{% extends 'main/base.html' %}
{% block app_content %}
    {{answer.question|safe}}
    {{answer.body | safe}}
    <div class="mt-3 border-bottom border-success">
        <h3 class="text-success">
            <i class="fa fa-check-circle text-success mr-3"></i>
            <span>Best Solution</span>
        </h3>
    </div>
    {{answer.answer|safe}}
{%endblock%}